FROM php:7.4-fpm

RUN apt-get update
RUN apt-get install -y zip
RUN apt-get install -y unzip
RUN apt-get install -y git
RUN apt-get install -y curl
RUN apt-get install -y vim
    
# Install MySQLi
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

# Install PDO
RUN docker-php-ext-install pdo_mysql

# Composer installing
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/ \
    && ln -s /usr/local/bin/composer.phar /usr/local/bin/composer


COPY ./php.ini /usr/local/etc/php/conf.d/php.ini

WORKDIR /var/project

# CMD cd /var/project
# CMD php artisan db:seed --class=StorageFilesSeeder
# CMD php artisan migrate:fresh --seed