FROM nginx:latest

# Nginx Adding  image_filter module 
ADD ./nginx.conf /etc/nginx/nginx.conf
ADD ./project/nginx.conf /etc/nginx/conf.d/default.conf
# End Nginx Adding  image_filter module 

# RUN nginx -V
# RUN nginx -t

# RUN nginx -s reload
# RUN service nginx restart

WORKDIR /var/project